sudo: false
language: go
go:
  - 1.9.4
  - tip
before_install:
  - go get github.com/modocache/gover
  - go get github.com/mattn/goveralls
script:
  - go test -v github.com/jbub/banking/bban -coverprofile=bban.coverprofile
  - go test -v github.com/jbub/banking/country -coverprofile=country.coverprofile
  - go test -v github.com/jbub/banking/iban -coverprofile=iban.coverprofile
  - go test -v github.com/jbub/banking/swift -coverprofile=swift.coverprofile
  - gover
  - goveralls -coverprofile gover.coverprofile -service travis-ci
branches:
  only:
    - master
matrix:
  allow_failures:
    - go: tip